# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

upx:
  - enabled: true
    goos: [linux]
    goarch: [arm64, amd64]
    compress: 1
    lzma: false
    brute: false

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README*
      - LICENSE*
      - deploy/goshawk.service
      - example_config.yaml

nfpms:
  - formats:
      - rpm
      - archlinux
    bindir: /usr/bin
    description: "Goshawk server monitoring tool"
    maintainer: "Goshawk"
    license: "MIT"
    contents:
      - src: deploy/goshawk.service
        dst: /usr/lib/systemd/system/goshawk.service
      - src: example_config.yaml
        dst: /etc/goshawk.yml
        type: "config|noreplace"
        file_info:
          mode: 0600
    rpm:
      signature:
        key_file: private.key
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-1.{{ .Arch }}"

aurs:
  - name: goshawk-bin
    disable: '{{ eq .Env.AUR_KEY "" }}'
    homepage: "https://github.com/gonimals/goshawk"
    description: "Goshawk server monitoring tool"
    maintainers:
      - "nicovell3 <nicovell3@gmail.com>"
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/goshawk-bin.git'
    provides:
      - goshawk
    conflicts:
      - goshawk
    backup:
      - etc/goshawk.yml
    package: |-
      options=('!strip' '!debug')
      install -Dm755 goshawk "${pkgdir}/usr/bin/goshawk"
      install -Dm644 deploy/goshawk.service "${pkgdir}/usr/lib/systemd/system/goshawk.service"
      install -Dm600 example_config.yaml "${pkgdir}/etc/goshawk.yml"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
